import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Criador de Tickets</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <div className={styles.text}>
          <h2>Envie o seu ticket para o suporte agora mesmo. <p>É só clicar na aba <i>Faça o seu ticket</i></p></h2>
        </div>

        <div>
          <Image
            width={672}
            height={433}
            src='/images/banner.jpg'
            alt='suporte banner'
          />
        </div>
      </section>
    </div>
  )
}

export default Home
